### ISSUE TITLE
君の旅行は UI Review

### ISSUE THREAD

**Issue by Sangun-Kang** [Ikuzo-KiminoRyokouha/kiminiryoukouha-web#72]
## GG
- 전체적으로 Padding / Margin이 너무 좁아요. 여러분들만의 디자인 시스템을 한번 정해보는게 좋을 것 같습니다.
- font-family 설정하기
```css
// 기본적으로 자주쓰는 폰트패밀리 CSS 코드. 최상위에 적용시키세요.
font-family: "IBM Plex Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
```
- 헤더 스크롤 이벤트 발생시 background-color 재정의 하기
- 전체적으로 Padding / Margin 넣기
   - 숫자 자체는 요소별로 통일 시킬 것
   - 예) input 16px / card 24px / Button 8px 16px 등등....
- border-radius를 어느정도 통일 시킬 것
  - 각 요소의 테두리의 통일감을 주는 것으로 확 UI가 살아요
- input UI에 padding을 넣어주는 것 추천
   -  적당히 바꿔본 것
<img width="339" alt="image" src="https://user-images.githubusercontent.com/71971007/217268809-2f4ac256-2100-4ac0-a0cb-b58b96ad1679.png">

```css
.input {
    padding: 8px 16px;
    border-radius: 4px;
    border: 1px solid;
    border-color: #9d9d9d;
}
.button {
    border-radius: 4px;
    background: rgb(25, 118, 210);
    padding: 8px 16px;
    box-shadow: rgb(0 0 0 / 20%) 0px 3px 1px -2px, rgb(0 0 0 / 14%) 0px 2px 2px 0px, rgb(0 0 0 / 12%) 0px 1px 5px 0px;
}
```
- 각 component의 디자인을 조금 손 보기
  - input / button / cart 등 반복적으로 쓰이는 부분은 component화 시키기
  - 참고하기 좋은 사이트
  - [머터리얼 디자인](https://m3.material.io/)
  - [뉴모피즘 UI](https://demo.themesberg.com/neumorphism-ui/
  - 가장 좋은건 [MUI](https://mui.com/)같은 UI 프레임워크를 사용하는게 좋지만, 이미 개발이 많이 진행됬으므로..참고해주세요. 많이 도움될거에요
- Google Icon/font 적극 활용하기
  - https://fonts.google.com/
  - https://fonts.google.com/icons 

외에 직접 디자인 목업을 만들어 준다든가 하는건..제 능력부족 시간부족으로..불가능...❤️

디자인 시스템에 대한 것도 재미있으니 찾아서 여러분들 만의 디자인 시스템을 간단하게 정의해봐도 재미있을거에요. (이건 완전 디자인영역)
